let text = `Oct 13, 2021; Your 24th birthday, and a great throwback to our (sometimes tumultuous) times at Carlos Sr's. This is where our love stood its first true test and thankfully we made it out largely unscathed. This was a great peek into how caring you are as a person, and the lengths you go for the people you love ❤️. Also shoutout the surprise gift from Iz 🍩!
Oct 24, 2021; The really random and super fun party in SF! You look absolutely adorable and this was overall a super fun night turning up with SAME. You got to see a glimpse of my true klepto side 😏
Oct 27, 2021; Our one Ramen Nagi experience! There are very few things I enjoy more than eating delicious food with you 🍜
Oct 30, 2021; OKAY MAEVE WILLIAMS!!! You looked hot AF and got the pose perfect. Sadly your costume was outshined (literally) by my golden opulence 👑
Nov 4, 2021; Our favorite restaurant in Redwood City. You honestly look so fkin adorable I can'tttt (nice jacket too 👀). We should go back here soon, although will it ever be the same now that you're vegetarian? The honey sausage is the move... 
Nov 4, 2021 (cont.); The very short lived attempt at you teaching me how to sew (had to lookup how to spell this lol). You look very Russian here
Nov 14, 2021; YES SUR. What a beautiful place and amazing weekend. Particularly enjoyed the ice cream in that really cool cafe by the water, camping the previous night, seeing DOLPHINS, wrecking your car and ziptying it back together, and Vince randomly being there lol
Nov 14, 2021 (cont.); My first and only Terun experience, food was good but price was wack. Just a cute picture of you, mid experience overall xD
Dec 2, 2021; HANGING OUT WITH WENDY AND JASON (RIP 😭). Playing cards (that left hand of the red baron or whatever game, weird) and delicious mapo tofu I think?? Fun night overall and cute pic of the four of us 🥹. Nice jacket
Dec 7, 2021; SHOUTOUT GEO! Putting us up with the sickest holiday event, delicious free sliders and drinks and watching Encanto together ❤️. Nice jacket (also our plates look a little excessive)
Dec 25, 2021; Merry Christmas 🎄!!! It's difficult to summarize this entire stay in Boston with few enough words such that the text box doesn't overflow the image, but en bref: being with your family and feeling the warmth of your home truly meant the world to me, and gave me so much happiness. It reminded me of the few Christmases I got to experience with my mom and dad back in Toronto, and made me feel loved and included and a part of something. I deeply missed it as soon as I left. Thank you so much for having me in your home and letting me experience the holidays with the love of your family ❤️. Some highlights: all the delicious food Mila made, playing tres patas and the other aguinaldos (damn am I fluent?), coming up with all the gifts (real and joke), the walks along the Charles, and every minute I got to spend with you in your home. I miss Boston! Let's go back soon 😊
Jan 9, 2022; PINNACLES 🏔. What a great trip with an even greater crew (I really liked Elijah, tough). We successfully mounted the long and hard shaft of mountain without even breaking a sweat, went caving, used those railing things, and had great chats throughout this 8 hour hiking experience. Plus you look adorable in a cap 🥰
Jan 10, 2022; I don't even remember what movie we watched here, but shoutout this great theatre with delicious popcorn. Damn my hair looked good here 🥵
Jan 31, 2022; WENDY'S CHINESE NEW YEAR'S PARTY 🇨🇳, we absolutely stunted on everyone there and ate some delicious mapo tofu and dumplings. Gonna miss Wendy and Jason hosting these extravagant parties, the high life suits her. We also called my dad later this night, and it was really sweet of you to stay on the call with us 😊. I love you so much
Feb 12, 2022; Zazie with SAME! Really enjoyed eating $20 tiny portion breakfast (oh but tip was included!!!xD1!11!!) and your beautiful dead eyes 💓
Feb 14, 2022; VALENTINE'S DAY 💘, what an amazing day overall this was even though we almost broke up for some reason I can no longer remember xD. The delicious Alison Roman pasta and your amazing slutty fashion sense (I really like that shirt btw). I also don't know what that pose is but keep killing it sas 👌
Feb 17, 2022; Trying the Pho place by my house and some photo-ception. Honestly the food was pretty mid but the experience was a ten, and any time we get to eat together I'm happy. Nice jacket
Feb 19, 2022; Geraldine's birthday! This was honestly a very fun day even though we started hella late and it got dark quick. We look really cute in this photo and I miss that group, we've had some great times together 🫂. Dinner at your place after was amazing, cooking the SUMMER PASTA and drinking and chatting with everyone. Also I filmed you brushing your teeth for some reason, you must've been wasted
Mar 4, 2022; YOSEMITE WEEKEND. One of the highlights right off the bat was our 4 our drive up together, McDonalds breakfast a classic and getting to spend the first day just the two of us and explore the valley was such an amazing experience
Mar 4, 2022 (cont.); Seeing the falls and doing our wrong-direction loop hike was honestly a highlight of the weekend, not to mention the shenanigans we pulled off in our AirBnB later that night 👀😏. I love you so much!
Mar 5, 2022; Second day of Yosemite with Aaron and Maddy! Making snowmen in the field, seeing and exploring Lower Yosemite Falls, and our attempt at hiking up Yosemite falls getting thwarted by the weather. But we still got some amazing views in and a wonderful weekend overall
Mar 16, 2022; SHIZEN OMFG. Probably my favorite dining experience together in SF, but not sure if that was cause of the food or because of how smokin hot 🚭 you looked. I'll literally come eat here any time you want (I think I might owe you a Shizen dinner anyway??), so just hit me up whenever girl
Apr 3, 2022; Golden Gate Park! You looking beautiful under this cherry blossom tree, us picnicing by the Conservatory, walking and talking together throughout the park (one of my favorite activities to do together despite my general dislike of walking... should tell you how much I enjoy our talking 😉). I still need to bring my bike up so we can bike through the park together!
Apr 9, 2022; Wine tasting with Rains! Eating delicious fudge, drinking delicious 18% sugary port, you looking GORGEOUS in Nancy's dress, and a beautiful sunny day. Could life get any better??
Apr 9, 2022 (cont.); Yeah, that's my girlfriend. She's fine af 🔥
Jun 1, 2022; Well it appears I skipped two key events when selecting these photos: the Lizzo concert on Apr 19 (lmao what an experience), and our first surfing experience together on May 22! Pretty big time skip here, I guess our relationship was on the rocks in April and May 😳. Surfing was pretty amazing, we both bawsed it up and killed it (pretty sure we both stood up more times than Nikki and caught more metres of surf travelled, suck it dumb hoe). <br><br> Anyway, about the photo at hand... my birthday! This was honestly such a great night, you getting to bond with my mom and spending time with her made me soooo happy. Feasting on a bunch of her cooking (needed salt xD), looking through baby photos (so cliché), you seeing where I grew up (WEIRD!), all very necessary and memorable experiences I will look back on
Jun 1, 2022 (cont.); My girlfriend with my two other girlfriends 👩‍👩‍👧‍👦😏. Love how great you are at getting along with all my ex lovers, and you and Jiasi are SO cute together. Really random bar but great to see everyone and give them all Covid. Also we were really living it up in that high rise Sonder downtown! The entire Montreal trip was, despite the circumstances, extremely fun. Just getting to spend time with you cooped up in our high rise apartment and play house, our brief illegal and immoral walks in the mountain, and visit to the Botanical Gardens (shortened edition) were all splendid. We're going back soon unhampered by illness and tearing up the whole city with our litness. Also was very cool to merge my life in Montreal with my life with you once again, and the more I do it the more I love seeing it all together 🥰
Jun 17, 2022; PARISSSSSSSS. What an absolutely incredible trip. First of all, love the dress. Starting the trip off right with the most delicious meal (IMO) of the visit, looking fly af and stunting on all the Parisians. A long day of travel and the crazy heat couldn't stop us, and omg the escargot and fois gras was to DIE for
Jun 17, 2022 (cont.); THE SEINE what an amazing day of walking and visiting the Eiffle tower (out of view 😉). Our airbnb was cute as hell and so were we
Jun 18, 2022; Delicious macarons (macaroons?) and visiting the Arc de Triomphe, you wearing my favorite dress of all time probably (definitely top 3) and a load of walking. Even though we woke up at 2pm (shoutout to the blackout blinds), this was still probably my favorite day of our entire trip. Why's that? Scroll to find out...
Jun 18, 2022 (cont.); THE MOTHAFOKIN BOAT CRUISE (and aftermath). Sasa even though we basically broke up and fought like crazy on this boat cruise, and the food wasn't as good as the night before, and we didn't have the best seat in the house because one of us was constantly scrunched up.. hm what was I gonna say? (cringe writing) crying together while drunk and on a mini island by the Seine has to have been my most cherished memory of this trip. Groping u in public (what else is new) and even more walking until we ended up at...<br><br>LE LOUVRE omg sasa if this wasn't the MOST beautiful walk of our entire relationship I don't know what can beat it. Walking in golden hour while drunk and emotional and seeing the gorgeous Parisian architecture, art, and nature legit made me want to move to Paris on the spot. And we literally made a pact to do it (I think we have a problem with committing to things). The walk to the Louvre and sitting by the fountain was honestly no cap my FAVORITE memory of Paris and the most beautiful thing I've ever experienced in my entire life
Jun 19, 2022; I like it when you make this face it's cute. Walking along the Seine after a nice morning in the Louvre where we fought again and almost broke up and then had a very tense dinner after this. hm it seems like we fought quite a lot at the start of this trip xD
Jun 20, 2022; OUR CHARCUTERIE BOARD PICNIC in the Luxembourg Gardens, delicious bread, meat, and cheese with a beautiful view of the park and the weird zonal grass sitting laws. We ate so much good food and got so chubs it was great
Jun 21, 2022; My next favorite memory of Paris, Montmartre! Loved this town on a hill and seeing the beautiful Sacre-Coeur, eating our croque madames. You rocked the fit and the bag looks killer 💯
Jun 22, 2022; THE SECOND TOWER YOU RODE THAT DAY 😏 what an incredible and beautiful (BASIC WHITE TOURIST) experience. Honestly I think I really like climbing stairs though because this was super fun and an like an elevated form of hiking, and worth it for the crazy elevation and views (yes I like being high in the sky)
Jun 22, 2022 (cont.); racism
Jun 22, 2022 (cont.); Paying $18 for water which was a big rip (fk Evita for the suggestion) but the food was very peng and it was cute seeing your social anxiety flourish when talking to the hostess. This was our last full day in Paris together which capped off an incredible trip with the love of my life. Going back to Google Paris the next day and stealing snacks for Dede was the perfect way to end it
Jul 3, 2022; PRAYSSACCCCCCC also an amazing trip and was great to spend time with Dede and eat more delicious food. She was a very sweet host and her house was beautiful (send this to her xD). I loved La Recreation (hope that was the name), our bike rides across the countryside, seeing Dede's old white geriatric friends (and enemies @georgette), and eating all the bread and pate in the world
Jul 6, 2022; LONDON INNIT, WOW what an incredible place and honestly even though we didn't really get to spend that much time together (because Maddy was maliciously trying to infect us both with Covid) it was so nice to enjoy a pint on the Thames together (GOALS) and I know you had a super fun time with Maddy as well. A fitting way to end our 2022 Euro trip ❤️
Jul 16, 2022; US LOOKING SMOKING HOT 🔥 AT AMRITA'S BIRTHDAY PARTY
Jul 20, 2022; Another poke and boba date in the square, one of my favorite passtimes in Redwood. We really did make a great home out of this small & not-so-bumpin city
Aug 15, 2022; Lunch and dinner at Google SF together, nothing I like more in life than eating meals with you Sasa (especially when we have GREAT views and the food is free). You also look absolutely stunning in that jacket and shirt combo 🥵
Aug 23, 2022; Getting absolutely sauced out our minds with the TORT and PORT! Very lucky to have that beautiful rooftop and sky (nice earrings)
Aug 23, 2022 (cont.); you looking sauced tossed bent and demolished (but that bun tho 💦). remember when you used to beat me at gin. yeah me neither
Aug 27, 2022; BLACK SANDS BEACH we finally made it after all the attempts and visiting. Had a great day playing poker (you wiping the floor with me) and walking along the sand
Aug 27, 2022 (cont.); GETTING WAVY WITH OUR FAVORITE COUPLE AND THE BEST ROOMMATE IN 1007. We should go back to that sushi place, even though the drinks were kinda mid and the sake tasted like watered down poison and they take advantage of drunk people by adding a service charge AND still prompting you to tip, the entire night was super fun. Weirdest party we've ever been to followed up by getting wavy and meeting a bunch of people I don't remember and Jason yacking and then me yacking and also me saying I'd rape you, good times (dunno if it's smart to publicize this on the internet)
Sep 3, 2022; MOUNT TAMALPAIS beautiful hike and look at this photo I captured of the most valuable thing in my life and you carrying it so preciously. As much as I might not be the biggest fan of walking, I will ALWAYS love going on hikes with you 1-on-1. There are very few things that reaffirm my love for you as much as this does
Sep 11, 2022; 🌊🏄‍♀️ SHEESH hitting rips and catching waves and surfing water and getting up more times than she-who-shall-not-be-named (even though you didn't get up at all LOL). Good squad here
Sep 17, 2022; The fact that I included this photo and immortalized this horrific haircut should tell you how much I love you. This was a fun night and you looked stellar ✨ in that dress
Sep 18, 2022; WE FINALLY WENT TO THE MALL TOGETHER and shopped together and got over the crippling fear of me not liking your clothes! Glad we're able to do this together and you ended up picking out some pretty fire clothes. Also ur face lol
Oct 5, 2022; LinkedIn slash IPA sponsor model alert!! What a killer smile and what a fun event! Always love the interesting discourse we have around philanthropy and the likes, seeing you and Amrita's friendship, and randomly playing poker (you wiped the floor with us! Jason only won because I felt bad for him in the end). I love attending drinking events with you
Oct 8, 2022; Our most recent adventure together in Point Reyes. The incredible and elevated Sky camp, eating breakfast above the clouds (even though those benders stole camp 5 from us)
Oct 8, 2022 (cont.); Windswept on our private beach after a long roundabout hike to get to Wildcat. Taming Maeve, some dead jellies, using our pocket rocket and blasting off, WOW
Oct 8, 2022 (cont.); 😏😏 you already know ho
Oct 8, 2022 (cont.); Fingering you in the way you enjoy the most
Oct 9, 2022; Even though I was carrying like 10x your pack-weight we still had to rest for you but that's okay because I love you. And you look cute in this hat so it's okay. <br><br>I think you already know this from how much we talked about it this weekend, but I literally love you so much and cannot imagine a better life than the one I have with you right now. We have so much fun together and always build up and support each other in the best ways possible, and challenge each other when it's needed. I'm so happy to be able to call you my life partner, girlfriend, and best friend, and cannot wait for our upcoming years of life together. I truly think you will accomplish some incredible things in your lifetime, and I'm happy to be here and be able to be a part of it. You'll always have my full support and love no matter what. Happy birthday Sasa!`;

let parent = document.querySelector('#parent');
let leftTemplate = document.querySelector('#left-template');
let rightTemplate = document.querySelector('#right-template');
let numImages = 56;
let texts = text.split('\n');

for (let i = 0; i < numImages - 1; i += 2) {
    let l = leftTemplate.cloneNode(true);
    let r = rightTemplate.cloneNode(true);
    l.classList.remove('is-hidden');
    r.classList.remove('is-hidden');

    // Set the image and text.
    l.querySelector('img').src = `images/img${i}.jpg`;
    r.querySelector('img').src = `images/img${i + 1}.jpg`;
    if (texts[i] === undefined || texts[i+1] === undefined) {
        break;
    }
    let [leftDate, leftPar] = texts[i].split(';');
    let [rightDate, rightPar] = texts[i + 1].split(';');
    l.querySelector('.box').innerHTML = `<b>${leftDate}</b><br>${leftPar}`;
    r.querySelector('.box').innerHTML = `<b>${rightDate}</b><br>${rightPar}`;

    parent.appendChild(l);
    parent.appendChild(r);
}

window.addEventListener('load', function() { AOS.init(); });

